### ISSUE TITLE
Doesn't work well with other plugins

### ISSUE THREAD

**Issue by jhogendorn** [scottt732/coredns-traefik#1]
Sorry for nondescript title. Great plugin, but some issues?

- Does not work with finalize plugin
- Does not seem to work with log plugin

I find some clients cant cope with CNAMEs, and in trying to debug this I found these issues. Not sure whats resolvable here but keen to have a discussion.

**Comment by scottt732** [comment]
Sorry for the delay. I took a stab at implementing some new functionality that may help you. You can specify `a 10.0.0.2` instead of `cname traefik.homelab.net` and it will return A records instead of CNAMEs.

As far as the finalize plugin, it may have to do with the order specified in `plugin.cfg`. That said, with `a` you may not need it. I also added an `insecureskipverify` and `resolveapihost` options. These should let you convert something like this:

```
    hosts {
        10.10.10.2 traefik.homelab.net
        fallthrough
    }
    traefik https://traefik.homelab.net/api {
        cname traefik.homelab.net
        refreshinterval 30
        ttl 5
    }
```

to this:

```
    traefik https://traefik.homelab.net/api {
        a 10.10.10.2
        refreshinterval 30
        ttl 5
        resolveapihost
    }
```

or this:

```
    traefik https://10.10.10.2/api {
        a 10.10.10.2
        refreshinterval 30
        ttl 5
        insecureskipverify
    }
```

Let me know if any of these address your issue.

**Comment by jhogendorn** [comment]
I've rebuilt my container with the latest source, and swapped these settings over.

It's giving 'unknown property: refreshInterval', but if i comment that out its working with the a/resolveapihost flags.

honestly impressed with the quick response and feature, super cool. appreciated for sure.

happy to make another issue for this but the thought crossed my mind, it would be good if it could be configured to only import certain providers (like just file). the api for traefik does give provider information so its plausible. Just depends how ones architecture is setup and whats connected to what regarding dynamic services. But if routes are specified in a file thats kind of their source of truth and that needs to propagate to coredns via this plugin.

**Comment by scottt732** [comment]
Thanks! I'll take a look at the Traefik API and see what I can do re:
filtering.

Try changing refreshInterval to all lowercase. I realized while looking
around at the other plug-ins that corefiles seem to be all lowercase. I can
make parsing the block case insensitive though since this is a bit of a
breaking change.

**Comment by jhogendorn** [comment]
ah, the case change i did not spot. that did resolve it. thanks so much for the responsiveness and cool new features :)
